### PR TITLE
Feature/project finalization

### PR DESCRIPTION
**Pull request by SaadMahi**
Final project

### CODE REVIEW

**Comment by fayez-baig** [comment]
@SaadMahi You don't have to push node_modules

**Comment by fayez-baig** [comment]
don't merge this branch in main

**Comment by SaadMahi** [comment]
>You don't have to push node_modules

Yes after pushing later i figured it out, i will remove it no worries.

**Comment by SaadMahi** [comment]
> don't merge this branch in main

node_modules and build folder removed, kindly verify.

**Pull request merged**
